apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: vote-service
  name: vote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vote-service
  template:
    metadata:
      labels:
        run: vote-service
    spec:
      containers:
      - name: vote-service
        image: gcr.io/vigilant-cider-216913/vote-service:v1
        env:
        - name: STATS_SERVICE_TARGET
          value: dns:///stats-service:50061
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: vote-service
  name: vote-service
spec:
  ports:
  - name: grpc
    port: 50071
    protocol: TCP
    targetPort: 50071
  selector:
    run: vote-service
  type: LoadBalancer