apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: chat-client
  name: chat-client
spec:
  replicas: 2
  selector:
    matchLabels:
      run: chat-client
  template:
    metadata:
      labels:
        run: chat-client
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: chat-client
        image: gcr.io/vigilant-cider-216913/chat-client:v1
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        env:
        - name: STATS_SERVICE_TARGET
          value: dns:///stats-service:50061
        - name: CHAT_SERVICE_TARGET
          value: dns:///chat-service:50051
        - name: VOTE_SERVICE_TARGET
          value: dns:///vote-service:50071
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: chat-client
  name: chat-client
spec:
#  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    run: chat-client
  type: LoadBalancer